#!/usr/bin/python3

# novacut: the collaborative video editor
# Copyright (C) 2011 Novacut Inc
#
# This file is part of `novacut`.
#
# `novacut` is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# `novacut` is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for
# more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with `novacut`.  If not, see <http://www.gnu.org/licenses/>.
#
# Authors:
#   Jason Gerard DeRose <jderose@novacut.com>

"""
Script to fire-off a render.
"""

import optparse
import json
import os

# We run at a fairly low priority, so the UI stays responsive:
os.nice(10)

from gi.repository import GObject
import dbus
from dbus.mainloop.glib import DBusGMainLoop

import novacut


GObject.threads_init()
DBusGMainLoop(set_as_default=True)
session = dbus.SessionBus()


parser = optparse.OptionParser(
	version=novacut.__version__,
)
(options, args) = parser.parse_args()
job_id = args[0]

novacut.configure_logging()

from novacut.worker import Worker
worker = Worker()
d = worker.run(job_id)
print(json.dumps(d, sort_keys=True, indent=4))
