#!/usr/bin/python3

# novacut: the collaborative video editor
# Copyright (C) 2011 Novacut Inc
#
# This file is part of `novacut`.
#
# `novacut` is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# `novacut` is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for
# more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with `novacut`.  If not, see <http://www.gnu.org/licenses/>.
#
# Authors:
#   Jason Gerard DeRose <jderose@novacut.com>

import optparse

from userwebkit import BaseUI

import novacut


index = 'index.html'

parser = optparse.OptionParser(
    version=novacut.__version__,
)
parser.add_option('--benchmark',
    help='benchmark app startup time',
    action='store_true',
    default=False,
)
parser.add_option('--page',
    help='starting page to load; default={!r}'.format(index),
    default=index,
)
(options, args) = parser.parse_args()


class UI(BaseUI):
    app = 'novacut'
    page = options.page
    splash = 'splash.html'
    title = 'Novacut'
    databases = ['novacut', 'project']
    
    
ui = UI(options.benchmark)
ui.run()
