#!/usr/bin/python3

# novacut: the collaborative video editor
# Copyright (C) 2011 Novacut Inc
#
# This file is part of `novacut`.
#
# `novacut` is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# `novacut` is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for
# more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with `novacut`.  If not, see <http://www.gnu.org/licenses/>.
#
# Authors:
#   Jason Gerard DeRose <jderose@novacut.com>

"""
Script to fire-off a render.
"""

import argparse
import json
import os
import logging

from dmedia.service import get_proxy

import novacut
from novacut.render import Worker


logging.basicConfig(
    level=logging.DEBUG,
    format='\t'.join([
        '%(levelname)s',
        '%(processName)s',
        '%(threadName)s',
        '%(message)s',
    ]),
)
log = logging.getLogger()


# We render at a fairly low priority, so the UI stays responsive:
os.nice(10)

parser = argparse.ArgumentParser()
parser.add_argument('job_id')
parser.add_argument('--version', action='version',
    version=novacut.__version__,
)
args = parser.parse_args()


Dmedia = get_proxy()
env = json.loads(Dmedia.GetEnv())
worker = Worker(Dmedia, env)
result = worker.run(args.job_id)

print(json.dumps(result, sort_keys=True, indent=4))

